### ISSUE TITLE
YOLOSuperNet test result error

### ISSUE THREAD

**Issue by laymond1** [laymond1/yolov7-nas-for-TANGO#5]
- yolov7.pt의 state_dict를 YOLOSuperNet의 state_dict에 일대일 매칭한 후, test.py의 test 함수를 실행시켜 coco128에 대해 성능을 도출하였을 때, 0이 나옴.
![image](https://github.com/laymond1/yolov7-nas-for-TANGO/assets/30643471/f7ea55bd-bd1c-499d-92ff-79283bf6d029)

- yolov7.pt를 활용하여 test 함수를 실행하면 제대로 된 성능이 나옴.
![image](https://github.com/laymond1/yolov7-nas-for-TANGO/assets/30643471/7317e1f6-c6af-4018-bb62-0a74ae7a5015)

**Comment by feVeRin** [comment]
지금 정의된 supernet.yaml 파일 마지막 구조가 기존 yolov7.yaml 구조랑 살짝 다른것으로 보여요
state_dict에서 전체 named key개수가 supenet이 566개고 yolo가 560개인데, 그림처럼 딱 마지막 6개 Idetect layer가 차이나거든요. 그래서 앞에 560개 key까지는 매치가 되는데, supernet 상으로는 마지막 idetect layer 6개가 매치 안 되어서 성능이 안나오는 것 같아요

- supenet
![image](https://github.com/laymond1/yolov7-nas-for-TANGO/assets/96801095/bb826d71-ad09-46b0-b0d6-0b018e48919c)

- yolo
![image](https://github.com/laymond1/yolov7-nas-for-TANGO/assets/96801095/5d57df9c-6f25-4b8c-bf25-6914583f7636)

(결론) supernet yaml 파일 마지막 부분을 Detect layer로 바꿔주면 될 것 같습니다.

**Comment by laymond1** [comment]
해당 내용도 이미 체크 해봤고, 위의 결과가 Detect layer로 했을 때의 결과임.



> 확인해봤는데 지금 정의된 supernet.yaml 파일 마지막 구조가 기존 yolov7.yaml 구조랑 살짝 다른것으로 보여요 state_dict에서 전체 named key개수가 supenet이 566개고 yolo가 560개인데, 그림처럼 딱 마지막 6개 Idetect layer가 차이나거든요. 그래서 앞에 560개 key까지는 매치가 되는데, supernet 상으로는 마지막 idetect layer 6개가 매치 안 되어서 성능이 안나오는 것 같아요
> 
> * supenet
>   ![image](https://user-images.githubusercontent.com/96801095/238216652-bb826d71-ad09-46b0-b0d6-0b018e48919c.png)
> * yolo
>   ![image](https://user-images.githubusercontent.com/96801095/238216672-5d57df9c-6f25-4b8c-bf25-6914583f7636.png)
> 
> (결론) supernet yaml 파일 마지막 부분을 아래 그림처럼 Detect layer로 바꿔주면 될 것 같습니다. ![image](https://user-images.githubusercontent.com/96801095/238216943-99d56d62-4237-4d78-9bda-b22b3de81f02.png)

**Comment by feVeRin** [comment]
NAS 코드 말고 따로 detection 결과 뽑아보면 동일하게 나오는데 뭐가 문제인지 모르겠네요;;;

- yolo
![image](https://github.com/laymond1/yolov7-nas-for-TANGO/assets/96801095/e0ae8208-39c7-4d1a-8166-8ed832fabe57)

- weighted supernet
![image](https://github.com/laymond1/yolov7-nas-for-TANGO/assets/96801095/1c7ec41b-673f-4360-bcf1-73b2397f51ec)

**Comment by laymond1** [comment]
어떤 걸로 했는데 저 결과가 나온거지? 나는 detect.py로 해도 예측을 못 해내는데.

**Comment by laymond1** [comment]
- 원인 파악 완료! 
- yolov7.yaml에서 정의한 ELAN 블록의 cadinality concat 방식과 우리 코드 ELAN 블록의 cadinality concat 방식이 반대로 되어 있어 ELAN 블록 코드 수정 완료.

![image](https://github.com/laymond1/yolov7-nas-for-TANGO/assets/30643471/a6eb9e5f-84af-4997-be01-7391b1e620fd)
